+incdir+src/macros
src/graphics_engine/graphics_engine_pkg.sv
src/game_logic/game_logic_pkg.sv
src/graphics_rom/graphics_rom_pkg.sv
src/graphics_engine/vgatiming.sv
src/graphics_engine/render_engine.sv
src/game_logic/enemy_movement.sv
src/graphics_rom/ghost_sprite.sv
src/graphics_rom/ghost_sprite_generated.sv
src/graphics_rom/crosshair_sprite.sv
src/main.sv
src/project.sv
